import { Component, Input } from '@angular/core';
import { LegalIconComponent } from '../legal-icon/legal-icon.component';

@Component({
 selector: 'portal-preview', standalone: true, imports: [LegalIconComponent],
 template: `<div class="laptop" aria-label="Illustrative portal preview"><div class="screen"><aside><div class="mini-brand"><legal-icon name="scale"/> DIGITAL LAW FIRM</div>@for(item of (student ? studentMenu : menu); track item){<div class="menu-item" [class.selected]="$first"><span>◈</span>{{item}}</div>}</aside><div class="workspace"><div class="topbar">Your workspace <span>◉ &nbsp; <b>AH</b></span></div><div class="welcome"><small>Welcome back,</small><h4>{{student ? 'Learn. Practice. Build your future.' : 'Your legal journey matters.'}}</h4><span class="preview-label">ILLUSTRATIVE PREVIEW</span></div><div class="metrics">@for(item of (student ? studentMetrics : metrics); track item.label){<div><legal-icon [name]="item.icon"/><strong>{{item.value}}</strong><small>{{item.label}}</small></div>}</div><div class="panels"><div><h5>{{student ? 'Continue learning' : 'Recent activity'}}</h5>@for(item of (student ? lessons : activity); track item){<div class="activity"><i></i><span>{{item}}</span><small>View →</small></div>}</div><div><h5>Quick actions</h5>@for(item of (student ? studentActions : actions); track item){<div class="quick">⊕ <span>{{item}}</span></div>}</div></div><div class="bottom"><legal-icon name="shield"/> Your workspace. All in one place.</div></div></div></div><div class="base"></div>`,
 styles: [`:host{display:block;width:100%;color:#12304a;font-family:Inter,Arial,sans-serif;font-size:10px;line-height:1.4}.laptop{border:8px solid #17222d;border-radius:15px 15px 5px 5px;background:#17222d;box-shadow:0 25px 50px #00132655}.screen{display:flex;background:#f5f8fc;min-height:295px;border-radius:6px;overflow:hidden}aside{width:25%;background:#062940;color:#bfcedb;padding:15px 10px}.mini-brand{font:8px Georgia;display:flex;align-items:center;gap:5px;color:#e9c984;margin-bottom:22px}.mini-brand legal-icon{font-size:15px}.menu-item{font-size:8px;padding:10px 6px;display:flex;gap:8px;border-radius:4px}.selected{background:#17547c;color:white}.workspace{width:75%;padding:0 16px}.topbar{padding:10px 0;border-bottom:1px solid #e3e9ee;font-size:7px;display:flex;justify-content:space-between;align-items:center}.topbar b{background:#ddc69b;padding:5px;border-radius:50%;color:#08253c}.welcome{padding:16px 0 12px;position:relative}.welcome small{font-size:8px}.welcome h4{font:bold 12px Georgia;color:#102d46;margin:4px 0}.preview-label{font-size:5px;letter-spacing:1px;color:#7a8791}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.metrics>div{background:white;border:1px solid #e6ecf2;border-radius:4px;padding:9px 5px}.metrics legal-icon{color:#389b8b;display:block;font-size:9px;margin-bottom:4px}.metrics strong{font-size:12px;display:block}.metrics small{font-size:6px;color:#6b7b8a}.panels{display:grid;grid-template-columns:1.35fr 1fr;gap:10px;margin-top:16px}.panels>div{background:white;padding:9px;border-radius:4px}.panels h5{font-size:8px;color:#143550;margin-bottom:6px}.activity{font-size:6px;display:flex;align-items:center;gap:5px;padding:8px 0;border-bottom:1px solid #edf0f3}.activity i{width:5px;height:5px;border-radius:50%;background:#369e7c}.activity small{margin-left:auto;font-size:5px;color:#8997a4}.quick{font-size:8px;color:#357eb6;padding:6px 0}.quick span{font-size:6px;color:#294861;margin-left:3px}.bottom{font-size:6px;display:flex;align-items:center;gap:4px;color:#7e8c97;padding:12px 0}.base{height:12px;background:linear-gradient(#a8b2bb,#dae0e3 45%,#617581);margin:0 -3%;border-radius:0 0 60% 60%;box-shadow:0 15px 24px #00152633}@media(max-width:480px){.screen{min-height:260px}.workspace{padding:0 8px}.menu-item{font-size:6px}.mini-brand{font-size:6px}.panels{gap:5px}.activity{font-size:5px}.welcome h4{font-size:10px}}`]
})
export class PortalPreviewComponent {
 @Input() student = false;
 studentMenu = ['Dashboard', 'My courses', 'Assignments', 'Certificates', 'Resources', 'Community'];
 studentActions = ['Explore courses', 'Continue learning', 'View resources', 'My progress'];
 menu = ['Dashboard', 'Cases', 'Consultations', 'Documents', 'Appointments', 'Messages', 'Payments'];
 metrics = [{icon:'briefcase',value:'24',label:'Total cases'},{icon:'users',value:'18',label:'Active matters'},{icon:'calendar',value:'12',label:'Appointments'},{icon:'file',value:'08',label:'Documents'}];
 studentMetrics = [{icon:'book',value:'06',label:'My courses'},{icon:'file',value:'12',label:'Assignments'},{icon:'cap',value:'03',label:'Certificates'},{icon:'users',value:'04',label:'Achievements'}];
 activity = ['Document submitted','Hearing date scheduled','Legal opinion received','Payment completed'];
 lessons = ['Introduction to constitutional law','Legal research fundamentals','The art of legal drafting','Understanding court procedures'];
 actions = ['Book a consultation','Upload documents','Track my case','Chat with lawyer'];
}


